config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/login', :to => "devise/sessions#new"
    get '/signup', :to => "devise/registrations#new"
    delete '/logout', :to => "devise/sessions#destroy"
  end

  get 'welcome/index'

  mount Spree::Core::Engine, :at => '/store'

  root to: "welcome#index"

  Spree::Core::Engine.routes.draw do
     resources :reviews
     post 'update_reviews', to: 'reviews#update_reviews'
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  def self.display
    Review.where("display = ?", true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  after_filter :setup_spree_session_var

  protected

  def setup_spree_sessions_var
    if resource.persisted?
      session[:spree_user_signup] = true
    end
  end
end

app/controllers/spree/home_controller.rb
module Spree
  class HomeController < Spree::StoreController
    helper 'spree/products'
    respond_to :html

    def index
      @searcher = build_searcher(params.merge(include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
      @body_id = "home-body"
      @reviews = Review.display.shuffle
      @new_review = Review.new
    end
  end
end

app/controllers/spree/reviews_controller.rb
module Spree
  class ReviewsController < Spree::StoreController
    def index
      if current_spree_user && current_spree_user.admin?
        @reviews = Review.all.sort_by(&:created_at)
      else
        flash[:error] = "You cannot go there!"
        redirect_to root_path
      end
    end

    def create
      review = Review.new(review_params)
      if review.save
        flash[:notice] = "Thank you for reviewing our product!"
        redirect_to root_path
      else
        flash[:error] = "Something went wrong with recording your review."
        redirect_to root_path
      end
    end

    def destroy
      review = Review.find(params['id'])
      review.delete
      redirect_to reviews_path
    end

    def update_reviews
      review_arrays = params['review_data']
      review_arrays.each do |review_hash|
        review = Review.find(review_hash['id'])
        display_value = review_hash['display'].present?
        if review.display == display_value
          next
        else
          review.update_attribute(:display, display_value)
        end
      end
      redirect_to reviews_path
    end

    private

    def review_params
      params.require(:review).permit(:description, :name, :email, :city, :state)
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "kapitolreef"
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kapitol Reef: The Cadillac of Snorkels</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/reviews/index.html.erb
<%= form_tag update_reviews_path do %>
  <div class="row">
    <% @reviews.each do |review| %>
      <div class="panel panel-default review-panels-admin">
       <div class="panel-heading">
         <%= "#{review.name} from #{review.city}, #{review.state} wrote:" %>
       </div>
       <div class="panel-body">
        "<%= "#{review.description}" %>"
       </div>
       <div class="panel-footer clearfix">
        <%= hidden_field_tag "review_data[][id]", review.id %>
        <%= check_box_tag("review_data[][display]", value = true, checked = review.display) %>
        <%= label_tag(:display, "Include on shop home page") %><br>
        <%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger pull-right' %>
       </div>
      </div>
    <% end -%>
  </div>
  <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <div class="container">
        <div class="navbar-form navbar-right">
          <%= submit_tag "Update Reviews", class: 'btn btn-warning' %>
        </div>
    </div>
  </nav>
<% end -%>

app/views/spree/shared/_header.html.erb
<div id="spree-header">
    <div class="container">
      <%= render :partial => 'spree/shared/main_nav_bar' if store_menu? %>
    </div>
</div>

app/views/spree/shared/_login_bar.html.erb
<% if spree_current_user %>
  <li>
    <%= link_to Spree.t(:logout), spree_logout_path, :method => :delete %>
  </li>
<% else %>
  <li>
    <%= link_to Spree.t(:login), spree_login_path %>
  </li>
  <li>
    <%= link_to Spree.t(:signup), spree_signup_path %>
  </li>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>